#!/bin/bash
# Author: doOnline - D. van Dooijeweert
# Version: 1.0.1
# Website: https://www.doonline.nl
# Dependencies: (Are installed by the installer.sh)
# - Java-jdk-8
# - Wget
# - Streama

# Script Variables
_NAME=`basename $0`;
_AUTH='doOnline';
_VERS='1.0.0';
_DESC='Exec for streama-daemon, current version '"$_VERS"' maintained by '"$_AUTH"'.';

# Configuration Variables
_DEBUG=1;

# Static variables
_LIB_NAME="streama";
_BIN_DIR="/usr/local/bin";
_LIB_DIR="/usr/local/lib/$_LIB_NAME";

_DAEMON="$_LIB_DIR/bin/controller";

_DAEMON_START="$_LIB_DIR/bin/start-daemon";
_DAEMON_STOP="$_LIB_DIR/bin/stop-daemon";
_DAEMON_LOG="$_LIB_DIR/bin/log-daemon";

_STREAMA_START="$_LIB_DIR/bin/start-streama";
_STREAMA_STOP="$_LIB_DIR/bin/stop-streama";
_STREAMA_LOG="$_LIB_DIR/bin/log-streama";

# Exit bash script.
exit 0;
